### ISSUE TITLE
key_layout script shows all layouts, not current

### ISSUE THREAD

**Issue by victorz** [vivien/i3blocks-contrib#107]
This is in reference to: `i3blocks-contrib/key_layout/key_layout`

### Expected behavior

Expect to get the current keyboard layout

### Actual behavior

It shows both of my layouts: "`us,se`"

### i3blocks config relevant to blocklet(s)

Irrelevant

### Output of blocklet(s) when run from command line

"`us,se`"

### Output of any relevant other commands that might help diagnostics

```bash
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,se
options:    terminate:ctrl_alt_bksp,grp_led:scroll,grp:alt_shift_toggle,ctrl:nocaps
```

**Comment by kb100** [comment]
setxkbmap doesn't provide any way to tell which layout is the current one when using toggling. If you want to use `grp:alt_shift_toggle`, then you should try the alternate blocklet which can handle this

https://github.com/vivien/i3blocks-contrib/tree/master/kbdd_layout
