### ISSUE TITLE
Volume-pulseaudio block is not vertically centered in status bar

### ISSUE THREAD

**Issue by fhdummy** [vivien/i3blocks-contrib#109]
### Expected behavior

The volume-pulseaudio block is vertically centered in the status bar. 

### Actual behavior

The volume-pulseaudio block is not vertically centered in the status bar. Instead, it is truncated on the top. All other blocks are vertically centered. See this image:

![selection_001](https://user-images.githubusercontent.com/13376172/30018479-4d1ff8ea-915d-11e7-9c8e-a13835556f32.png)

### i3blocks config relevant to blocklet(s)

~/.i3blocks.conf:

```
[volume-pulseaudio]
command=$HOME/scripts/i3blocks/volume-pulseaudio/volume-pulseaudio -a
interval=once
signal=1
```

~/.config/i3/config:

```
bar {
        status_command i3blocks
        i3bar_command i3bar -t
        position bottom
}
```

### Output of blocklet(s) when run from command line

```
$~/scripts/i3blocks/volume-pulseaudio$ ./volume-pulseaudio -a
  50% [1:ALC3235 Analog]
  50% [1]
#ffffff
```

### Output of any relevant other commands that might help diagnostics

i3 version 4.13-277-g86b7183 (2017-08-28, branch "gaps-next") © 2009 Michael Stapelberg and contributors

i3blocks 1.4 © 2014 Vivien Didelot and contributors

**Comment by kb100** [comment]
Well the output of the block is correct, so there's probably not anything we can do about it unless it's a simple font problem. Do you have fontawesome installed? See if the problem still exists when you run it with

    command=$HOME/scripts/i3blocks/volume-pulseaudio/volume-pulseaudio -a -H "" -M "" -L "" -X ""

**Comment by kb100** [comment]
Also try

    command=$HOME/scripts/i3blocks/volume-pulseaudio/volume-pulseaudio -a -H "<span font='FontAwesome'>  </span>"

at high volume. If that also fixes it (at high volume), then I know what to do.

**Comment by fhdummy** [comment]
Hello,

thanks very much for the response. The issue was that I didn't have fonts-font-awesome (this is the package under Ubuntu 16.04) installed. Thank you.

**Comment by Georgantas** [comment]
Another thing to try that solved it for me: make sure the input to i3blocks is in unix format and not dos format. You can do this easily by piping the output to the "unix2dos" utility before sending it to i3blocks.
