### ISSUE TITLE
Calendar renders below screen on click.

### ISSUE THREAD

**Issue by Hritik14** [vivien/i3blocks-contrib#115]
### Expected behavior
Calendar should render above mouse pointer and should be visible. (As shown in screenshot)

### Actual behavior
Calendar renders below mouse pointer and goes out of visible screen.

### i3blocks config relevant to blocklet(s)
```[rofi-calendar]
command=$SCRIPT_DIR/rofi-calendar
label=
interval=3600
```

**Comment by kb100** [comment]
@vKnmnn as the author of the blocklet, perhaps you could take a look at this issue.

**Comment by vKnmnn** [comment]
@Hritik14 try updating to the latest git version of rofi, and see if the problem persists.
There was an issue with the window placement in a previous version.

**Comment by vKnmnn** [comment]
@Hritik14 can you please report back?

**Comment by Hritik14** [comment]
Fixed. Thanks.
