### ISSUE TITLE
battery script showing only wrong battery number

### ISSUE THREAD

**Issue by stef204** [vivien/i3blocks-contrib#117]
This is in reference to "battery" / "battery.py" script (not the original battery script)

### Expected behavior
Show proper (and only/single) battery status in i3 bar (currently 96% for example)

### Actual behavior
Shows status for "wrong battery or battery number [although there is only 1 battery]" (currently 32% for example)

### i3blocks config relevant to blocklet(s)
[battery]
command=~/bin/battery/battery
markup=pango
interval=30

### Output of blocklet(s) when run from command line
`% ./battery
<span font='FontAwesome'></span> <span color="#FF9900">32%</span>
<span font='FontAwesome'></span> <span color="#FF9900">32%</span>`

### Output of any relevant other commands that might help diagnostics
` % acpi -b
Battery 0: Discharging, 0%, rate information unavailable
Battery 1: Unknown, 96%
Battery 2: Discharging, 0%, rate information unavailable`

`%uname -sr
Linux 4.13.4 `

```
% ibam -ra       
Bios percentage:            97 %
Battery percentage:         96 %
Soft low percentage limit:  5 %
Charge percentage:          88 %
Bios time left:              1:56:24
Battery time left:           1:38:30
Adapted battery time left:   1:45:15
Charge time left:            0:17:52
Adapted charge time left:    0:16:43
Total battery time:          1:42:25
Adapted total battery time:  1:49:26
Total charge time:           2:23:01
Adapted total charge time:   2:13:50
```

Ibam detects battery correctly.

So does `%dstat --battery`

Small app called Qbat as well.

**Comment by kb100** [comment]
Hmm, (0+96+0)/3 = 32, so the script is working as intended. The issue here is that acpi is reporting that you have 3 batteries, and that 2 of them are at 0%. Perhaps it would be best to report battery percentage as the average of nonzero battery percentages? Would this suit your needs?

**Comment by kb100** [comment]
Or would an option to manually specify the battery number be better?

**Comment by stef204** [comment]
Thanks for feedback.
Average of non zero batteries would seem best.

**Comment by kb100** [comment]
Sorry for the delay. Would you please test my proposed fix at https://github.com/kb100/i3blocks-contrib/commit/150f4b9dc7a7f32e621d0cc2f67b2571b7e2847f

**Comment by stef204** [comment]
Thank you.  Applied the patch and testing now.  Give me a day or 2 to make sure behaves correctly under different circumstances and will report back soon.

**Comment by stef204** [comment]
It seems to work OK in detecting the proper charge % now.  One thing I noticed, is that if I unplug power, it does not show the "time remaining" every time.

```
% acpi i
Battery 0: Discharging, 0%, rate information unavailable
Battery 1: Discharging, 97%, 01:53:36 remaining
Battery 2: Discharging, 0%, rate information unavailable

It only shows the battery icon and "97%".

If I reboot and then startx with power unplugged, it will show the full text, i.e. % and time left.

**Comment by kb100** [comment]
https://github.com/kb100/i3blocks-contrib/commit/bb5e464a028cbae6accb2fceab6f8a803d892522

Try that commit. It takes time remaining from the first battery that reports it.

**Comment by stef204** [comment]
```
% ./battery
<span font='FontAwesome'></span> <span color="#FFFFFF">83%</span> (01:31)
<span font='FontAwesome'></span> <span color="#FFFFFF">83%</span> (01:31)
```
Looks OK, thank you.
