### ISSUE TITLE
mediaplayer shows "(null) - (null)" when no player is open

### ISSUE THREAD

**Issue by lukeoftheaura** [vivien/i3blocks-contrib#119]
### Expected behavior
Showing nothing when no player is running.

### Actual behavior
Showing "(null) - (null)" when no player is running

### i3blocks config relevant to blocklet(s)
```
[mediaplayer]
instance=Lollypop
interval=5
signal=10
```

### Output of blocklet(s) when run from command line
nothing if player is running. If no player is running an error of no players found.

**Comment by kb100** [comment]
Does the block work at all? I'm not sure that Lollypop is supported. Could you also run
 
    playerctl --player=Lollypop metadata artist
    echo $?
    playerctl --player=Lollypop metadata title
    echo $?

in three following situations: no player running, player running but not playing, player playing.

**Comment by lukeoftheaura** [comment]
player not running:
```
(null)0
(null)0
```

player not playing:
```
0
0
```

player playing:
```
Aphex Twin0
We are the music makers0

```

**Comment by kb100** [comment]
In the script, lines 122 and 128, can you add the following two chomps as indicated and see if this fixes the issue

    my $artist = qx(playerctl $player_arg metadata artist);
    chomp($artist)

    ...

    my $title = qx(playerctl $player_arg metadata title);
    chomp($title)

**Comment by lukeoftheaura** [comment]
my script is only 77 lines - do I have an older version?

**Comment by kb100** [comment]
Yes you must have an old version. The version in this repo has 154 lines. I thought I remembered fixing this issue before. Just update and that will fix it.

**Comment by lukeoftheaura** [comment]
updating has fixed this problem.
