### ISSUE TITLE
Include default scripts

### ISSUE THREAD

**Issue by vivien** [vivien/i3blocks-contrib#122]
In order to simplify the maintainability of i3blocks and prevent duplicates, it would be preferable to move the default scripts out of the i3blocks repository into this i3blocks-contrib repository.

Things to do:
* move scripts and handle duplicates (e.g. what we want to do with the *bandwidth* script?)
* add a default configuration file in the root directory pointing to default scripts
* remove scripts from i3blocks source

@kb100, would you mind if I assign this to you?

**Comment by kb100** [comment]
I am happy to do this. I will probably get it done this weekend.

 I will keep the names of all the default blocklets as they appear in the main repo now. I will rename conflicting named blocklets in the contrib repo. For config files, what naming convention would you like? Just `config` or `i3blocks.conf` or something else? I will also read your other issue more carefully soon.

As a side note, some of the blocklets require compilation (bandwidth2 comes to mind, I will have to check if any others do) so just keep that in mind in case a package maintainer needs to coordinate.

Also, some blocklets require outside dependencies, another fact that requires no specific action at the moment but is relevant for maintainers to keep in mind.

**Comment by vivien** [comment]
Thanks @kb100. Let's hold on this until we figure out what is the best thing to do for default scripts in #121.

**Comment by vivien** [comment]
I think we are good to go. What I'll do next is providing an helpful message directly in the status bar if there is no config file found or no blocklet, so that running i3blocks the first time won't feel like an error to the users.

> For config files, what naming convention would you like? Just config or i3blocks.conf or something else?

I think we must use something which avoids any conflict with the user configuration and updates (e.g. `git pull`). The simplest step I can think of after installing i3blocks for a lazy user is:

````
$ git clone git@github.com:vivien/i3blocks-contrib.git ~/.config/i3blocks
$ cd ~/.config/i3blocks
$ cp config.example config
$ i3-msg restart
````

So I'd suggest a suffixed name like `config.example` to encourage users to copy it and avoid conflicts in the future. What do you think?

**Comment by kb100** [comment]
I think a `config.example` or perhaps even a few example configs `minimal_config.example`, etc. could be used. What about the configs provided in each blocklet directory though? Same convention with `config.example`?

**Comment by vivien** [comment]
Indeed we can imagine per-distro config files like `debian.config.example` using the apt-upgrade blocklet, etc. For the `config` files provided in each blocklet, there are unfortunately here just for documentation purpose, so I think keeping `config` is fine, that is up to you ;-)

**Comment by kb100** [comment]
All default scripts included.
