### ISSUE TITLE
Scrolling in volume-pulseaudio isn't working properly

### ISSUE THREAD

**Issue by dikiaap** [vivien/i3blocks-contrib#136]
If I use scroll's click, I can't use toggle mode now. It just muted and can't unmuted again. But if on the keyboard it works.

And when scrolling volume, the percentage volume becomes increased and decreased than before, but not when using the keyboard. Previously is like 5%→10%→15%. Now 5%→7%→8%→10%→14%

The output of some commands from https://github.com/vivien/i3blocks-contrib/commit/ee9986f252fd6ceaa0dd33fb197ef168c730ef3d
- `amixer info | head -1 | cut -d ' ' -f 2` is default 
- `amixer -D "default" scontrols | sed -n "s/Simple mixer control '\([^']*\)',0/\1/p" | head -n1` is Master 
- `amixer -D default get Master | sed -n "s/ Capabilities:.*cvolume.*/Capture/p"` has no output

**Comment by kb100** [comment]
Interesting behavior... could post the output of the blocklet when you run it from the command line please?

    #regular
    ./volume-pulseaudio

    #scroll up and down
    BLOCK_BUTTON=4 ./volume-pulseaudio
    BLOCK_BUTTON=5 ./volume-pulseaudio

    #toggle mute twice
    BLOCK_BUTTON=2 ./volume-pulseaudio
    BLOCK_BUTTON=2 ./volume-pulseaudio

Hopefully there are some helpful errors.

**Comment by kb100** [comment]
As a side note, if the issue is what I think it is (script wrongly things your mixer is "default" instead of "pulse"), you can temporarily fix this by editing the script and hard coding

    MIXER=pulse
    SCONTROL=Master
    CAPABILITY=""

**Comment by dikiaap** [comment]
Here's the output:
```shell
~/.local/bin/i3blocks/volume-pulseaudio on  master 
 $ ./volume-pulseaudio

  29% [0:analog-stereo]
  29% [0]
#ffffff

~/.local/bin/i3blocks/volume-pulseaudio on  master 
 $ BLOCK_BUTTON=4 ./volume-pulseaudio
  33% [0:analog-stereo]
  33% [0]
#ffffff

~/.local/bin/i3blocks/volume-pulseaudio on  master 
 $ BLOCK_BUTTON=5 ./volume-pulseaudio
  29% [0:analog-stereo]
  29% [0]
#ffffff

~/.local/bin/i3blocks/volume-pulseaudio on  master 
 $ BLOCK_BUTTON=2 ./volume-pulseaudio
  29% [0:analog-stereo]
  29% [0]
#a0a0a0

~/.local/bin/i3blocks/volume-pulseaudio on  master 
 $ BLOCK_BUTTON=2 ./volume-pulseaudio
  29% [0:analog-stereo]
  29% [0]
#a0a0a0
```

**Comment by kb100** [comment]
Could you investigate the behavior of

    amixer -q -D $MIXER sset $SCONTROL 5%+ 

and 

    amixer -q -D $MIXER sset $SCONTROL toggle 

on your computer, trying different values for $MIXER and $SCONTROL? $MIXER is usually default or pulse, and $SCONTROL is usually Master, pulse, or Pulse.

**Comment by dikiaap** [comment]
From your previous comment. Yeah, that's what I thought. That works if I edit the script like that. I just do not want to get into merge conflict if there is a new commit.

No, I didn't set the environment variable of $MIXER.

Also this is my amixer info:
```shell
$ amixer info
Card default 'SB'/'HDA ATI SB at 0x90440000 irq 16'
  Mixer name	: 'Realtek ALC270'
```

**Comment by dikiaap** [comment]
So what I think after test both devices is when I scroll volume, I incresase both volumes of the device.

This is before toggle mode, the output volume in a bar is 73% and volume is active:
```shell
$ amixer -D default sget Master      
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 76 [87%] [-8.25dB] [on]

$ amixer -D pulse sget Master        
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 47751 [73%] [on]
  Front Right: Playback 47751 [73%] [on]
```
Then when I do a toggle mode with scroll's click, it just mute "pulse" and "default" volume:
```shell
$ amixer -D default sget Master
Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 87
  Mono: Playback 76 [87%] [-8.25dB] [off]

$ amixer -D pulse sget Master  
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 47751 [73%] [off]
  Front Right: Playback 47751 [73%] [off]
```
When I turned it back with scroll's click again, nothing happened and still mute.

**Comment by kb100** [comment]
I see... well the commit that is causing this issue for you was put in place to solve a similar issue for someone else (myself included) because either pulse people or alsa people switched conventions at some unknown version. Honestly, we don't know of an automatic way to tell what the correct $MIXER and $SCONTROL values are because it apparently depends on a huge number of variables, including version of pulse, version of alsa, and even what distro you are using. :(

For now, see the new commit and use the `-m` and `-s` options.
