### ISSUE TITLE
possible include others than yaourt into "arch-update" 

### ISSUE THREAD

**Issue by thyeun** [vivien/i3blocks-contrib#148]
as per title, can it be flexible to change yaourt on "arch-update" to others?

an example, aurman, packer, and etc

**Comment by kb100** [comment]
Theoretically yes, but someone would have to write that code and we are busy people :(. If you want to write it yourself and submit a PR, make sure to read https://github.com/vivien/i3blocks-contrib/issues/132 first and comply with the new setup. Sorry for all the confusion, we are trying to migrate to a new system so this branch of the repo is frozen for now.

**Comment by thyeun** [comment]
@kb100 yes, i'm wrote one for the ```packer``` but somehow i'm still stuck on the ```right click mouse``` to bring up the ```urxvt terminal``` and exec ```packer -Syu```

need some help on this, below is the code
```
#used for displaying count/status in the i3blocks
output()
{
    package_list=$(packer --quickcheck)
    package_count=$(packer --quickcheck | wc -l)
    if [ $package_count -eq 0 ]; then
        echo "Up To Date"
    else
        echo "upgrades: $package_count"
    fi
}
#used for notify-send messaging when clicking i3blocks entry
notify_output()
{
    if [ $package_list -eq ""]; then
        $(notify-send -t 2000 "Upgrades:" "No Upgrades Found!")
    else
        $(notify-send "Upgrades:" "$package_list")
    fi
}

#defines i3blocks mouse click events
case $BLOCK_BUTTON in
    # left click to update & list packages
    1) output && notify_output ;;
    #middle click to update i3blocks status without display
      #2) output ;;
      # right click: run upgrade then refresh i3blocks
    2) urxvt -e 'packer -Syu' && output ;;
esac
```

**Comment by thyeun** [comment]
@kb100 make it work, but not using ```urxvt terminal``` , i change it to ```xfce4-terminal```, have to figure out how to use urxvt.

**Comment by thyeun** [comment]
@kb100, make it work now, so how to submit as new alternative 'arch-update"?

**Comment by CNG** [comment]
My quick hack: I am using `aurman` and edited L.65 to be:

    output = check_output(['aurman', '-Qu']).decode('utf-8')

**Comment by kb100** [comment]
If you are having trouble launching a program like urxvt from within a blocklet, the recommended way to do it is using `i3-msg -q exec your_command`

**Comment by thyeun** [comment]
@kb100 my bad, i should close this instead of still let it open,  really sorry
