### ISSUE TITLE
mpd not working

### ISSUE THREAD

**Issue by yuceltoluyag** [vivien/i3blocks-contrib#152]
I try mpd but not working. i3block panel does not seem
playerctl installed
script installed
```
# Blocks
# Display current song
[mediaplayer]
command=~/.config/i3/blocks/mediaplayer
instance=mpd
interval=5
signal=10
```

**Comment by chrisalcantara** [comment]
I am experiencing the same issue. 

@carnager evening putting mpc in the instance does nothing.

So far, I just have (null) - (null) appearing in the bar. I know someone else filed an issue about that, but he or she was using Lollypop, not mpd.

**Comment by carnager** [comment]
You misunderstood me. What I meant was: mpc needs to be installed (The command line mpd client)

**Comment by chrisalcantara** [comment]
@carnager I already have the mpc command line tool installed. That is how I'm playing and pausing the music right now.
