### ISSUE TITLE
Kbdd blocklet isn't updated before i3 is restarted.

### ISSUE THREAD

**Issue by FredrikAugust** [vivien/i3blocks-contrib#165]
### Expected behavior
Kbdd should automatically detect when the keyboard is changed, and change accordingly.

### Actual behavior
Kbdd blocklet isn't updated before I restart i3.

### i3blocks config relevant to blocklet(s)
[kbdd]
command=/home/[cencored]/.i3/scripts/kbdd_layout

### Output of blocklet(s) when run from command line
Correct output.

**Comment by kb100** [comment]
Could you elaborate? You mean when you unplug your keyboard and plug in a new keyboard? Or you mean when the layout is changed? Kbdd is supposed to detect such changes so if this is not happening please let me know what method you are using to change the layout. Is it the one that is specified in the docs for the blocklet?

**Comment by FredrikAugust** [comment]
No @kb100; when I restart the computer and change the kbbd layout, the layout shown doesn't update until I restart i3.

**Comment by kb100** [comment]
What method you are using to change the layout? Is it the one that is specified in the docs for the blocklet?

**Comment by FredrikAugust** [comment]
Fixed it by moving the `xsetkbmap` config from `/etc/X11/xorg.conf.d/...` to an `exec` statement in `.i3/config`. Thanks.
