### ISSUE TITLE
Capitalized entries (dynamic properties?) in the `i3blocks.conf` file break the status line

### ISSUE THREAD

**Issue by Aster89** [vivien/i3blocks-contrib#173]
**After reading the small section _A blocklet doesn't work or I've found a bug, how can I best report it?_ at the FAQ page, I hope I'm not wrong in assuming this is the right place to post this question about a non-working option in a blocklet.**

It's been a while since last time I monkeyed around with i3blocks. Now I tried to download and use the `gpu-load` script, in the way it is suggested in the corresponding [`README.md`](https://github.com/vivien/i3blocks-contrib/tree/master/gpu-load), and it apparently works, as long as I keep the lines
```
#T_WARN=70
#T_CRIT=90
```
commented, otherwise I get the error (obviously appearing in place of the expected status line.)
```
Error: satus_command process exited unexpectedly (exit 1)
```

Experimenting a bit I've noticed that this happens for other blocklets as well, which all have these (commented) "capitalized" lines in their `i3blocks.conf` entry (it was not the case last time I tinkered with it). I hope not to be wrong in assuming that this problem is related to what I read in the `README.md`,
```
Note: i3blocks now supports dynamics properties,
and all scripts have been updated to do the same.
i3blocks-contrib requires a version of i3blocks that
supports dynamics properties, so upgrade as necessary.
```
but I think I've not done anything esotic since last time I installed a blocklet.

My version of `i3blocks` (installed by `sudo pacman -S i3blocks`) is the following
```
$ i3blocks -V
i3blocks 1.4 © 2014 Vivien Didelot and contributors
```
and I've copied the `gpu-load` script and its entry in the `i3blocks.conf` file from the `master` branch.

Btw, I've also clicked on the the link in the [`i3blocks` 's webpage](https://github.com/vivien/i3blocks/) about what were the "official" scripts (the link is in the line starting with _You can use your own scripts, or the ones provided with i3blocks._), but it is broken.

**Comment by jolange** [comment]
Version 1.4 does not support the dynamic properties yet. You'll either need to use the current git version of i3blocks or wait for the next release until you can use the scripts in the current format as contained in the master branch of this repository.

**Comment by Aster89** [comment]
I imagined this, but then I supposed it could not be that way since I read _Each release of this repository will be guaranteed to work against a given release of i3blocks (a.k.a. core)._ on the i3blocks-contrib page. There I understood that the master branches of the two repos should be guaranteed to work with each other. Have I missed something?

**Comment by kb100** [comment]
@Aster89, the master branch of i3blocks now also supports dynamic properties, and we coordinated to make both repos make the change at the same time, so indeed right now the master branch of both should work with each other. Right now is a bit hectic for us so please be understanding (and, even better, help us!).

**Comment by Aster89** [comment]
@kb100 , I really thought I was barking up the wrong tree when I read the 3 by 2 table.

Well, I'd be glad to help you, but I think I'm not at that level yet. Actually I've done a small edits to my blocklets, but they're all about fancy stuff. In this respect, I'd really appreciate if you could provide me with some reference where I could start from to understand this (vague to me) thing of "dynamic properties".

Maybe it's nice to tag @vivien as well, so he can read about the broken link without his issues page being clogged with small detail issues.

**Comment by kb100** [comment]
You can read about dynamic properties here: https://github.com/vivien/i3blocks-contrib/issues/132. The previous link is the guide I wrote to myself to help convert blocks form the old format to the new one. Basically, i3blocks now passes all `property=blah` things in the config as variables to your script, instead of just command, full_text, signal, instance, etc.

**Comment by Aster89** [comment]
Just for curiosity, if those capitalized names just define variables to be used in the scripts, putting them in the i3blocks config file without editing the blocklets scripts should result simply in unused variables, shouldn't it? Instead it breaks the i3blocks output. Maybe the reason is that i3blocks can't parse those options yet?

**Comment by kb100** [comment]
@Aster89 the old version of i3blocks cannot parse new dynamic properties, so it crashes. In the current version of i3blocks, if you add in extra options they will just be unused variables.

**Comment by vivien** [comment]
Thanks @Aster89, the new documentation is in progress and should be out very soon.
