### ISSUE TITLE
bandwidth: Consider state UNKNOWN as state UP

### ISSUE THREAD

**Issue by simonszu** [vivien/i3blocks-contrib#174]
The bandwidth script shows if the default route interface is UP or DOWN. This works great for interfaces with hardware related state, e.g. Wifi or ethernet. Other interfaces, like VPN or mobile network don't have this state, so they show UNKNOWN against the kernel, which is rendered as DOWN by the iface script. This looks weird when acutally using this interface.

### Expected behavior
Network interfaces which are in use shouldn't be shown as DOWN

### Actual behavior
Interfaces without hardware related state are provided as UNKNOWN by the kernel, which is interpreted as DOWN by the bandwidth script, although the interface has an IP address and real throughput

### i3blocks config relevant to blocklet(s)
```
[bandwidth]
label=
interval=1
color=#83d0c9
```

### Output of blocklet(s) when run from command line
```
$ ./bandwidth                                                                                                                                                                          Mi 19 Sep 2018 09:59:42 CEST
tun0 down
tun0 down
#FF0000
```

### Output of any relevant other commands that might help diagnostics

```
$ ip link                                                                                                                                                                              Mi 19 Sep 2018 09:59:45 CEST
7: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 100
    link/none 
```

**Comment by kb100** [comment]
Hmm thanks for pointing this out. I can add an option to have unknown display as up but this feels wrong to me. Right now is a very busy time though, so please be patient.
