### ISSUE TITLE
Battery script stopped working

### ISSUE THREAD

**Issue by archvill** [vivien/i3blocks-contrib#178]
Today after sleep I noticed that i3blocks battery indicator stopped working, it was freezed on 14% when my laptop was fully charged. I had to update this check in my `/usr/lib/i3blocks/battery` battery script (Arch Linux):

```
if ($acpi !~ /: (\w+), (\d+)%/) {
        die "'$acpi'\n";
}
```
to
```
if ($acpi !~ /: ([\w\s]+), (\d+)%/) {
        die "'$acpi'\n";
}
```

Acpi output was
```
Battery 0: Discharging, 0%, rate information unavailable
Battery 1: Not charging, 100%
Battery 2: Discharging, 0%, rate information unavailable
```

I've tried battery2 but it shows some unprintable characters (don't pay attention on html, I've disabled `markup=pango` to understand how it works)

![](https://habrastorage.org/webt/kc/lw/ox/kclwox4idw0ohidj2be5eshcxkq.png)

**Comment by kb100** [comment]
Thanks for the fix, I've included it.
