### ISSUE TITLE
bandwidth: doesn't print due to missing EOL

### ISSUE THREAD

**Issue by Aster89** [vivien/i3blocks-contrib#209]
### Expected behavior
Print the blocklet text

### Actual behavior
Doesn't print anything

### i3blocks config relevant to blocklet(s)
Not relevant, I think, but the following lines should, btw, not contain the quotes, since they get printed.
```
#INLABEL="IN "
#OUTLABEL="OUT "
```

### Output of blocklet(s) when run from command line
Empty string

### Output of any relevant other commands that might help diagnostics
A simple `echo` at the end of the script solves the problem, which comes from the non-eol-provided last command, which is either `printf` or `echo -n`.

**Comment by kb100** [comment]
You are right on both counts, no idea how this slipped by. Thank you very much for finding this. Fix incoming.

**Comment by kb100** [comment]
@Aster89 would you mind testing this fix?

**Comment by kb100** [comment]
Upon further investigation, i3blocks used to be fine with not emitting a newline at the end of blocks, this is no longer the case.

**Comment by Aster89** [comment]
1. Tested, it works
2. Yes, I think that blocklet has been peaceful for so long, so I guess you're right, it's i3blocks which doesn't spawn/flash/what'stherightverb the output anymore without a EOL.

**Comment by kb100** [comment]
Thanks for testing. No doubt some other blocks will have the same issue :(

**Comment by Aster89** [comment]
Couldn't you test my hopefully bugless improved version of `rofi-calendar`  :yum: ? With only the current month being available for inspection that blocklet revealed almost useless to me, especially when approaching the end of the month.

**Comment by jolange** [comment]
I just read this and another "no-newline-at-the-end causes trouble" issue came to my mind: #181.
In that case it was still visible, but the background color changed.

**Comment by kb100** [comment]
Actually in #181 it is the opposite problem, "too-many-newlines-at-the-end causes trouble". I just did some tests on it and awk always outputs a newline at the end, so manually printing one ended up in a double newline, which i3blocks interpreted as an empty background color.

**Comment by Aster89** [comment]
A brutal `print("\n");` (or something better) in `mediaplayer` is needed to, as long as I've tested (I've been noticing this behavior since I swithced from the normal `i3blocks` to the AUR version.

**Comment by kb100** [comment]
I'm a bit busy at the moment, but if you feel up to fixing any of these minor issues that would be a huge help. Or if you are also too busy, even making a separate issue (unlikely I will remember to look back at comments in this thread) would be helpful.
