### ISSUE TITLE
Is it possible to use the openvpn block with networkmanager-openvpn?

### ISSUE THREAD

**Issue by sultanofrum** [vivien/i3blocks-contrib#21]
I want to use networkmanager to manage my OpenVPN connection, as it's the only way I can get it to reliably restart after suspend. However, with this setup, the OpenVPN script in this repository just says 'down', even though vpn is working.

I can change the dev name of the vpn connection to 'tun0' instead of 'tun' in /etc/NetworkManager/system-connections/_vpn_id_ , but I don't know how to make it write a pid file.

Is there a way to make the [openvpn] block work with my setup?

Or is it easy enough to make a new block for this? i3status for example supports networkmanager-openvpn setups with this sort of configuration:

```
path_exists VPN {
        # path exists when a VPN tunnel launched by nmcli/nm-applet is active
        path = "/proc/sys/net/ipv4/conf/tun0"
}  
```

**Comment by kb100** [comment]
If all path_exists is doing is checking whether the file exists, that can be emulated in i3blocks with

    [vpn]
    command=[ -e $BLOCK_INSTANCE ] && (echo up; echo up; echo #00FF00) || (echo down; echo down; echo #FF0000)
    interval=10
    instance=/proc/sys/net/ipv4/conf/tun0

**Comment by sultanofrum** [comment]
Thank you very much, it works and is a lot more elegant than what I came up with!

I understand that just checking the path is much less sophisticated than what the openvpn blocklet in this package does, but that is all I can really manage at this state, having no knowledge in perl and almost none in bash or linux.

**Comment by kb100** [comment]
Perhaps @deimosfr (as far as I can tell, the original author of the openvpn script) would be interested in modifying his script to be compatible with networkmanager-openvpn? I personally have never used a vpn and thus am not well equipped to rewrite it myself.

**Comment by deimosfr** [comment]
Hi, yes I think I'm going to take a look about it as I'm using network manager too. I'll keep you updated

**Comment by sultanofrum** [comment]
Thank you very much, I am looking forward to it!

**Comment by deimosfr** [comment]
Hi,

I'm currently testing a quick trick for OpenVPN. Add this in a simple bash script file:
```
nmcli -t -f type,state,connection d | egrep '^tun|tap' | grep connected | awk -F':' '{ print "VPN: " $3 }' || echo 'VPN: down'
```
This requires nmcli of course. It doesn't support multiple VPN connections as NetworkManager doesn't too. Please let me know if it works for you too

**Comment by sultanofrum** [comment]
Seems to work great when VPN is up, but the 'VPN: down' message doesn't show when I turn it off from nm-applet.

**Comment by deimosfr** [comment]
Damn you're right! Please try this, this works on my side:
```bash
#!/bin/bash
result=$(nmcli -t -f type,state,connection d | egrep '^tun|tap' | grep connected | awk -F':' '{ print $3 }')
[[ -z $result ]] && echo 'VPN: down' || echo "VPN: $result"
```

**Comment by sultanofrum** [comment]
Thanks, seems to work perfectly now!

**Comment by deimosfr** [comment]
I let @vivien choosing the way he wants to purpose this new plugin

**Comment by deimosfr** [comment]
Here is better version:
```bash
#!/bin/bash
result=$(nmcli -t -f type,state,connection d | egrep "^(tun|tap):connected" | awk -F':' '{ print $3 }')
[[ -z $result ]] && echo 'VPN: down' || echo "VPN: $result"
```

**Comment by eyadsibai** [comment]
:+1:

**Comment by ralpheeee88** [comment]
@deimosfr  anyway we can display the actual connection name of vpn?

**Comment by deimosfr** [comment]
Mine doesn't show on/off. Yan you please send the output result of nmcli with args please.

**Comment by ralpheeee88** [comment]
@deimosfr  using an icon (padlock) for vpn
open https://i.imgur.com/n1yXhT9.png
closed https://i.imgur.com/qw5PxWo.png
scipt http://ix.io/sSg

**Comment by kb100** [comment]
https://github.com/vivien/i3blocks-contrib/pull/196 If this new block doesn't solve your issue please open a new one detailing why. Otherwise I'm closing.
