### ISSUE TITLE
Key indicators

### ISSUE THREAD

**Issue by ZZerog** [vivien/i3blocks-contrib#22]
Hi,

in readme https://github.com/vivien/i3blocks-contrib/blob/master/keyindicator/README.md section

[keyindicator]
instance=CAPS
interval=once
signal=11

Should it be 

[keyindicator]
command=/usr/local/libexec/i3blocks/keyindicator
instance=CAPS
interval=once
signal=11

instead? Thanks

**Comment by kb100** [comment]
keyindicator used to be an i3blocks script from the main repository, but it was migrated to i3blocks-contrib. Therefore, a fresh copy of i3blocks will not put the keyindicator script in `/usr/local/libexec/i3blocks/keyindicator`. Thus this does need to be fixed, but not in the manner you propose. Instead, a generic

    command=$SCRIPT_DIR/keyindicator

line will suffice. I will look into this an see if any other blocklets have this artifact as well. Thanks for noticing.

**Comment by jpleau** [comment]
Hi

I noticed some scripts have `command=./script' while others have `command=$SCRIPT_DIR/script`

Should we try to have them look all the same?

**Comment by kb100** [comment]
@jpleau This kinda bugs me too, I like `$SCRIPT_DIR` because I think it is more obvious that the user needs to change it, where just putting `./` they might think that that would literally work. We could start a separate pull request for this endeavor.
