### ISSUE TITLE
config.example gives `bad exit code 127`

### ISSUE THREAD

**Issue by keizanCole** [vivien/i3blocks-contrib#227]
### Expected behavior
For config.example to function like it's supposed to.

### Actual behavior
The only block that functions is `[time]`, everything else doesn't show. 

CLI output
[command_line_output.txt](https://github.com/vivien/i3blocks-contrib/files/3065591/command_line_output.txt)

### Additional Information
I have changed the `$SCRIPT_DIR` in the global `command` to point towards a blocklets folder that holds all aforementioned blocks in it but that is the only thing i've changed myself

**Comment by pataquets** [comment]
@0dad Same here. Did you solve this in the end?
I'm pulling my hair with the exact same problem and no clue about the cause, so far. Care to drop a pointer here?
Also, if it's some kind of possible tripping point for others, I'd like also to send a PR to document it for everybody else (and my future self :smile:), unless you fancy to do the PR yourself.
Thanks!
