### ISSUE TITLE
Mediaplayer does not seem to detect cmus

### ISSUE THREAD

**Issue by Quoding** [vivien/i3blocks-contrib#234]
### Expected behavior
Displaying the ARTIST - SONGNAME in the i3bar.

### Actual behavior
Nothing shows in the i3bar. No error, no fun.

### i3blocks config relevant to blocklet(s)
```
[mediaplayer]
command=/home/quo/.config/i3/scripts/mediaplayer/mediaplayer
instance=cmus
interval=5
signal=10
```

### Output of blocklet(s) when run from command line
Literally no output

### Output of any relevant other commands that might help diagnostics
Not an output but many other scripts work with i3bar/i3blocks, exactly 8 of them.

**Comment by thelazyoxymoron** [comment]
If somebody out there is still facing this issue, confirming that [kingelilol's](https://github.com/kingelilol) commit fixes it!

**Comment by Quoding** [comment]
Damn, I haven't checked since that commit. I'll close on your word and with the trace to the commit! Thanks for following up.
