### ISSUE TITLE
bandwidth blocklet does not work anymore

### ISSUE THREAD

**Issue by atk91** [vivien/i3blocks-contrib#252]
### Expected behavior
It should work

### Actual behavior
It does not display bandwith usage

### i3blocks config relevant to blocklet(s)
```
command=$SCRIPT_DIR/$BLOCK_NAME/$BLOCK_NAME

[bandwidth]
interval=10
```

### Output of blocklet(s) when run from command line
```
$ SCRIPT_DIR=/usr/lib/i3blocks i3blocks



```
(nothing at all)

### Output of any relevant other commands that might help diagnostics

```
$ /usr/lib/i3blocks/bandwidth/bandwidth
IN 5K OUT 1K
```

**Comment by LinArcX** [comment]
I have this problem too.
