### ISSUE TITLE
USB script not showing anything.

### ISSUE THREAD

**Issue by apoorv569** [vivien/i3blocks-contrib#353]
I'm trying to use the USB script provided here, running the script in shell outputs
```
❯ ./usb
Unknown device "/dev/└─/dev/sda": No such file or directory
Traceback (most recent call last):
  File "./usb", line 361, in <module>
    attributeMaps = getAttributeMaps(leaves)
  File "./usb", line 263, in getAttributeMaps
    return {path : makeAttributeMap(path) for path in paths}
  File "./usb", line 263, in <dictcomp>
    return {path : makeAttributeMap(path) for path in paths}
  File "./usb", line 252, in makeAttributeMap
    lines = check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['udevadm', 'info', '--query=property', '--name=└─/dev/sda']' returned non-zero exit status 1.
```
But, when I plug in a USB drive nothing shows up on the bar. It just stays like this even when no USB is connected.

![2020-08-13_04-06](https://user-images.githubusercontent.com/53279454/90075199-7466be00-dd1a-11ea-8c57-e40d961de5b5.png)

**Comment by zsugabubus** [comment]
Modified some other things since the last patch. Should work with it:

```diff
diff --git a/usb/usb b/usb/usb
index f74f0e4..a9f5e5f 100755
--- a/usb/usb
+++ b/usb/usb
@@ -95,18 +95,18 @@ def pangoEscape(text):
     return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

 def getLeafDevicePaths():
-    lines = check_output(['lsblk', '-spndo', 'NAME'], universal_newlines=True)
+    lines = check_output(['lsblk', '-lndpo', 'NAME'], universal_newlines=True)
     lines = lines.split("\n")
     lines = filter(None, lines)
     return lines

 def getKernelName(path):
-    return check_output(['lsblk', '-ndso', 'KNAME', path],
+    return check_output(['lsblk', '-lndo', 'KNAME', path],
             universal_newlines=True).rstrip("\n")

 def getDeviceType(path):
-    return check_output(['lsblk', '-no', 'TYPE', path],
-            universal_newlines=True).strip()
+    return check_output(['lsblk', '-lndo', 'TYPE', path],
+            universal_newlines=True).strip()

 def getFSType(path):
     global attributeMaps
```

**Comment by apoorv569** [comment]
> Modified some other things since the last patch. Should work with it:
> 
> ```diff
> diff --git a/usb/usb b/usb/usb
> index f74f0e4..a9f5e5f 100755
> --- a/usb/usb
> +++ b/usb/usb
> @@ -95,18 +95,18 @@ def pangoEscape(text):
>      return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
> 
>  def getLeafDevicePaths():
> -    lines = check_output(['lsblk', '-spndo', 'NAME'], universal_newlines=True)
> +    lines = check_output(['lsblk', '-lndpo', 'NAME'], universal_newlines=True)
>      lines = lines.split("\n")
>      lines = filter(None, lines)
>      return lines
> 
>  def getKernelName(path):
> -    return check_output(['lsblk', '-ndso', 'KNAME', path],
> +    return check_output(['lsblk', '-lndo', 'KNAME', path],
>              universal_newlines=True).rstrip("\n")
> 
>  def getDeviceType(path):
> -    return check_output(['lsblk', '-no', 'TYPE', path],
> -            universal_newlines=True).strip()
> +    return check_output(['lsblk', '-lndo', 'TYPE', path],
> +            universal_newlines=True).strip()
> 
>  def getFSType(path):
>      global attributeMaps
> ```

OK, its working, it was showing my HDD also(sda), so I added it to ignore list, it outputs as `[sdb] no partitions`. I think I prefer just a icon showing me that I have a USB device inserted. But anyways thanks!
