### ISSUE TITLE
i3 blocks manager

### ISSUE THREAD

**Issue by Fandekasp** [vivien/i3blocks-contrib#37]
It would be great to have a plugin like vundle for vim, or antigen for zsh, or tpm for tmux, where we'd only need to list the blocks we want to use (from their name or git path), and get them automatically happened.

That would probably be more useful as a i3 manager than a i3blocks one though.

**Comment by kb100** [comment]
Are you suggesting something that just downloads the blocks and puts them in a convenient location for you, or something that actually enables/disables blocks in your status line? The former seems reasonable to implement, the latter seems too complicated as many blocks require special setup and/or user configuration.

**Comment by Fandekasp** [comment]
I was thinking of the latter, but you're right, it will require efforts, and unfortunately I won't be able to contribute on this.
I'm not sure, however, if the former would really save the user some time. You would still need to search for the plugin, get its name/url, and write it down, instead of copy-pasting the code directly.

Thanks for the quick answer anyways, I appreciate the fast support :)

**Comment by kb100** [comment]
Perhaps there is a middle ground I'm not seeing but,

**Comment by kb100** [comment]
I agree that just a downloader wouldn't be much help. Perhaps there is a middle ground I'm not seeing, but I think most of the blocks require some user knowledge to set up. Only the "dumb" ones could be truly automated, so a manager would be tedious and involved.

I do wonder how much of a barrier the setup is. Do people view the READMEs and think "oh that's too complicated" and give up?

For now I don't see myself even attempting to implement a block manager. Of course if another contributor has the drive to do the hard part I'm willing to help however I can.

**Comment by jpleau** [comment]
We could have an .i3blocks.d directory, each blocklet would be a file starting with a number (to sort them)

ie: ~/.i3blocks.d/01-mpd.conf ~/i3blocks.d/02-battery.conf etc

With another directory somewhere where all the blocks are available, the "manager" would just symlink them to our .i3blocks.d directory (more or less)

But then i3blocks would have to add a feature to load blocklets like this.

**Comment by kb100** [comment]
Closing because not feasible anytime in the near future due to unique setup required by each blocklet. Feel free to reopen in future if enhancement becomes feasible.
