### ISSUE TITLE
[mediaplayer] Make playerctl a dependency

### ISSUE THREAD

**Issue by kb100** [vivien/i3blocks-contrib#38]
I don't see any mention of dependencies in the mediaplayer script, but it doesn't work on my machine. I think it doesn't work because I have no `playerctl`. I don't know what package this comes in, but I can't find it. Dependencies need to be added.

**Comment by quinnuendo** [comment]
I wrote down something like this a while ago, just never made a pull request (didn't separate it properly). 
https://github.com/quinnuendo/i3blocks-contrib/commit/9acff69fa323271cd1f41706551ff147b50343a6

I could do that now.

**Comment by quinnuendo** [comment]
Just made the pull request for this, it adds other details as well. #40

**Comment by kb100** [comment]
Fixed by https://github.com/vivien/i3blocks-contrib/pull/40
