### ISSUE TITLE
i3-focusedwindow using too much cpu and overheating device.

### ISSUE THREAD

**Issue by Ayush-pbh** [vivien/i3blocks-contrib#413]
# Expected behavior
Should Run properly. 

# Actual behavior
Runs as expected but this causes my cpu load to go to 50% on all 4 cores. and the temperature goes to 95 - 104. With nothing but a terminal running. Also when i comment it out, every thing goes to normal as it was.

# i3blocks config relevant to blocklet(s)
`
[greetings]
color=#f5af19
command=echo "नमस्ते , $USER!"
interval=once

[i3-focusedwindow]
label=[]=
command=/home/ayush/.config/scripts/i3-focusedwindow 20
interval=persist

#[documentation]
#full_text=
#command=xdg-open "https://www.youtube.com"
#color=#f12711
`
# Output of blocklet(s) when run from command line

[ayush@ayush-arch scripts]$ ./i3-focusedwindow 
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts
ayush@ayush-arch:~/.config/scripts

### Output of any relevant other commands that might help diagnostics
On running htop i get : [ImageLinkHere](https://imgur.com/a/G4sJBWD)

![htop-results](https://user-images.githubusercontent.com/43269920/128375495-682aa3ba-f6d1-407d-8ff6-d5cb43c29292.png)
Temperature Rising
![i3blocks-temp-issue](https://user-images.githubusercontent.com/43269920/128375630-0d6d2dbf-81b7-4d59-ae51-65c51daac1c1.png)

### System Properties

`
[ayush@ayush-arch i3blocks]$ neofetch 
 ayush@ayush-arch 
---------------- 
OS: Manjaro Linux x86_64 
Host: Latitude E6230 01 
Kernel: 5.10.53-1-MANJARO 
Uptime: 1 hour, 5 mins 
Packages: 1232 (pacman), 6 (snap) 
Shell: bash 5.1.8 
Resolution: 1366x768 
WM: i3 
Theme: Materia-dark [GTK2/3] 
Icons: Papirus-Dark [GTK2/3] 
Terminal: terminator 
CPU: Intel i5-3340M (4) @ 3.400GHz 
GPU: Intel 3rd Gen Core processor Graphics Controller 
Memory: 1596MiB / 3803MiB 
`

### Thank you for your support.

**Comment by cicervlvs** [comment]
Hello, did you ever find a solution to this? I'm having the same problem.

**Comment by Ayush-pbh** [comment]
No man, eventually I figured out that removing the focused window block solves the issue. So be it. Then i shifted to polybar. Suggest you the same.
