### ISSUE TITLE
volume-pipewire is not able to forward default sink when clicked on

### ISSUE THREAD

**Issue by initialxy** [vivien/i3blocks-contrib#422]
### Expected behavior
When clicked on, it should move to the next sink as default audio sink

### Actual behavior
Nothing happens

### i3blocks config relevant to blocklet(s)

    [volume-pipewire]
    interval=once
    signal=10

### Output of blocklet(s) when run from command line

    bash: (-1 + 0 + 1) % 0 : division by 0 (error token is "0 ")

### Output of any relevant other commands that might help diagnostics
Mismatched output from `pactl`.

I have a pull request for this. Logging an issue for tracking purpose. Please see pull request #421

**Comment by ktzee** [comment]
Looks like this has been merged? Maybe the issue can be closed?
