### ISSUE TITLE
key_layout toggle

### ISSUE THREAD

**Issue by yakir12** [vivien/i3blocks-contrib#45]
I have this line in my i3 config file in order to toggle between two keyboard layouts:
`exec --no-startup-id "setxkbmap -layout us,se -option 'grp:ctrl_alt_toggle'"`
But the query of setxkbmap's layout returns "us, se", so I never know what the current layout is (cause the block just shows "us, se"). What am I missing..?

**Comment by kb100** [comment]
After much searching, setxkbmap can only show you the layout rules, not the actual layout. Thus in order for this script to work as expected, you will have to have i3  symbind CTRL+ALT to a script that toggles between the layouts e.g. like the one here: https://superuser.com/questions/505466/2-and-more-keyboard-layout-groups-in-linux-changed-by-different-hot-keys

Sorry for this, I don't see any way to fix it at this time. Don't close the issue.

**Comment by yakir12** [comment]
For what it's worth, this works perfectly (for me):
in `.i3blocks.conf`:
```
[key_layout]
interval=once
command=~/.i3blocks/key_layout
signal=11
```
in `.i3/config`:
```
bindsym $mod+z exec --no-startup-id "~/.i3blocks/changeLayout && pkill -RTMIN+11 i3blocks"
```

and this `changeLayout` file is:
```
#!/usr/bin/env bash
LO=$(~/.i3blocks/key_layout)
if [ "$LO" == 'us' ]
then
        setxkbmap -layout se
else
        setxkbmap -layout us
fi
```

**Comment by kb100** [comment]
key_layout's functionality is now duplicated in the kbdd_layout script. key_layout works if you are switching between simple layouts (i.e. "us" is ok but not "us,se") , whereas kbdd_layout works when using group toggling.
