### ISSUE TITLE
Encfs request - usb

### ISSUE THREAD

**Issue by stef204** [vivien/i3blocks-contrib#46]
Might consider adding recognition of Encfs for usb script?

**Comment by kb100** [comment]
@stef204 I am the author and maintainer of the usb script. I've never worked with encfs before so would you please post the output of the following commands to help me assess whether this would be easy to add support.

Run each command with usb device plugged but encfs partition not mounted, and then again with encfs partition mounted:

    lsblk -spnd
    udevadm info --query=property --name=/dev/sdd
    udevadm info --query=property --name=/dev/sdd1

where /dev/sdd should be replaced by the usb device containing the encfs partition, and /dev/sdd1 is an encfs partition on said device.  Feel free to redact any information you do not wish to share. Currently the script mostly relies on lsblk being able to list the device and classify its type (disk/part/rom/crypt/etc.) and the ID_FS_TYPE attribute in the udev info.

**Comment by stef204** [comment]
I was making reference to showing whatever directory is mounted using encfs, just as the script shows mounted partitions e.g.  /mnt/shared (/dev/sdaX) on my box is a fat32 partition'.  Being able to see mounted encfs directories would be an enhancement.

Encfs is different so not sure it can be integrated; as it "is a userspace stackable cryptographic file-system similar to eCryptfs and uses FUSE to mount an encrypted directory onto another directory specified by the user. It does not use a loopback system like some other comparable systems such as TrueCrypt and dm-crypt". 

[https://github.com/vgough/encfs](url)

I tried to run each commands you suggested, modified to reflect proper parameters but nothing shows up since the directories are mounted using fuse (they are not really partitions so could be outside the scope of "usb script".  There might be a way to make these show up in the block though,)

Let me know what other steps you can suggest to help out.  Tx.

**Comment by kb100** [comment]
I'm closing this issue as out of scope of the usb script. However, what you suggest does seem like it could be a useful script in its own right. You may want to fork my usb script and re-purpose it.
