### ISSUE TITLE
[shutdown_menu] blocket disappears after mouse click

### ISSUE THREAD

**Issue by patrl** [vivien/i3blocks-contrib#57]
When using the [shutdown_menu] blocklet with rofi, the blocklet disappears after clicking on it. I haven't tested how it behaves with zenity, but I don't see why it should be any different. a simple fix is to echo the value of `full_text`, i.e.

`command=$SCRIPTS_DIR/shutdown_menu -c ; echo $FULL_TEXT`

I'll probably make a pull request at some point, but I'll leave this here in the mean time for anyone who experiences the same issue.

**Comment by kb100** [comment]
PR would be welcome. No idea how I didn't catch this in testing...

**Comment by kb100** [comment]
@patrl I've just tested this and the following config suggested in the `i3blocks.conf` for that blocklet works

    [shutdown_menu]
    full_text=Quit
    command=$SCRIPT_DIR/shutdown_menu -c

The blocklet does not disappear after clicking on it for me.

If this fixes your issue, please close the issue. Otherwise, please be more specific about how to get the text to disappear.

**Comment by patrl** [comment]
@kb100 are you using rofi or zenity? It could be a rofi specific issue. The issue is that when I click on the blocklet, the shutdown menu appears in rofi as expected, but if I exit the rofi menu using Esc without taking any action, the blocklet has disappeared. The issue occurs with the following `i3blocks.conf`, which as you can see, is the recommended config.

`[shutdown_menu]
full_text=
command=/home/patrl/GitHub/i3blocks-contrib/shutdown_menu/shutdown_menu -c`

The issue is fixed however and the blocklet persists after clicking on it but taking no action with the following `i3blocks.conf`:

`[shutdown_menu]
full_text=
command=/home/patrl/GitHub/i3blocks-contrib/shutdown_menu/shutdown_menu -c ; echo `

**Comment by kb100** [comment]
@patrl I've tested with rofi and with zenity and the text doesn't disappear for me after exiting the shutdown menu without taking any action. What version of i3 and i3blocks are you using?

**Comment by patrl** [comment]
Ah...OK, i'm really sorry, but I just realised that I'm using @Airblader 's fork of i3blocks (i3blocks-gaps-git from the AUR), which is based on version 1.4 of i3blocks. It presumably isn't supported. I have no idea what's behind this issue still, but please feel free to close.

**Comment by kb100** [comment]
I checked out the most recent version of i3blocks and indeed your issue is real.  A git bisect shows that the offending commit is https://github.com/vivien/i3blocks/commit/701dd3f704509278183090f9b3e66c546d5e0d68.
I will fix shortly
