### ISSUE TITLE
Can't cut kbdd_layout output down to 2 characters?

### ISSUE THREAD

**Issue by glubsy** [vivien/i3blocks-contrib#61]
I've been trying to cut down the output of [kbdd_layout](https://github.com/vivien/i3blocks-contrib/blob/master/kbdd_layout/kbdd_layout) down to only the first 2 characters of the active keyboard layout. 
My modifications work in terminal, the output is indeed what I want, but somehow i3blocks doesn't update properly. 

First modification on [line 37](https://github.com/vivien/i3blocks-contrib/blob/master/kbdd_layout/kbdd_layout#L37):
``````
echo $( ( dbus-send --print-reply=literal --dest=ru.gentoo.KbddService \
         /ru/gentoo/KbddService ru.gentoo.kbdd.getLayoutName uint32:$N ) | cut -c 4-5 )
``````
This works in i3blocks fine, I get "En" as expected for the initial state. 

But then, my second modification on [line 41](https://github.com/vivien/i3blocks-contrib/blob/master/kbdd_layout/kbdd_layout#L41):
``````
# Parse dbus output
dbus-monitor "interface='ru.gentoo.kbdd',member='layoutNameChanged'" | sed -un '0~2p' | \
        sed -un 's:.*string "\(.*\)".*:\1:p' | sed -u '/:/d' | sed -r 's/(.{2}).*/\1/'
``````
Even if I replace the last `sed` by a `cut -c '1-2'`, i3blocks doesn't update the output properly. Only this modification on line 41 makes this blocks to not work right. That last operation is causing issues, no matter which one it is...
Am I missing something obvious?

**Comment by kb100** [comment]
Since your changes work on the command line but not when called from i3blocks, I believe you are missing the fact that commands like sed have tricky caching optimizations that stop it from flushing stdout until some huge amount of data is accumulated first. Try using stdbuf, see e.g. https://github.com/vivien/i3blocks-contrib/blob/master/bandwidth/bandwidth, to stop commands doing such buffering.

**Comment by glubsy** [comment]
Thank you very much for the reply! 
Indeed `stdbuf`  did the trick. :+1: 

`dbus-monitor "interface='ru.gentoo.kbdd',member='layoutNameChanged'" | sed -un '0~2p' | sed -un 's:.*string "\(.*\)".*:\1:p' | sed -u '/:/d' | stdbuf -oL cut -c 1-2`

**Comment by kb100** [comment]
I will add an FAQ entry as this seems to be a common issue, you're not alone.
