### ISSUE TITLE
openvpn status always down

### ISSUE THREAD

**Issue by doctorcolossus** [vivien/i3blocks-contrib#67]
### Expected behavior
openvpn status show be 'up' when the openvpn interface is up

### Actual behavior
openvpn status is always down

### i3blocks config relevant to blocklet(s)
```
[openvpn]
interval=20
```

### Output of blocklet(s) when run from command line
```
down
down
```

### Output of any relevant other commands that might help diagnostics
I run openvpn with the packaged systemd service file, like this: "systemctl start openvpn@udp-ch.service". udp-ch indicates which configuration file to use; my configuration file is "/etc/openvpn/udp-ch.conf". It creates this pid: /run/openvpn@udp-ch.pid

I tried changing line 134 to:
`my @pid_file=glob '/run/openvpn@*.pid';`
... but then it says:
`Can't read config file 'udp-ch.conf': No such file or directory`

I don't really know perl, so I'm not going to dig deeper for now. I suppose it'd be easier to just check the status with systemctl or ifconfig. Just providing some feedback, in case you'd like to adapt this script to be useful to more people.

**Comment by kb100** [comment]
Please see my branch for attempting to fix: https://github.com/kb100/i3blocks-contrib/tree/67-fix/openvpn

The goal will be to make it so your config is 

    [openvpn]
    command=$SCRIPT_DIR/openvpn -p '/run/openvpn@*.pid';
    interval=20

and this works.

While your vpn is up, can you please post the contents of `/proc/<pid>/cmdline`, where `<pid>` is found in one of your "/run/opnvpn@*.pid" files.

**Comment by doctorcolossus** [comment]
The configuration you suggest produces the same error for me as I mentioned before:
`Can't read config file 'udp-ch.conf': No such file or directory`

```
$ cat /run/openvpn@udp-ch.pid 
13107
$ cat /proc/13107/cmdline 
/usr/bin/openvpn--cd/etc/openvpn--configudp-ch.conf--daemonopenvpn@udp-ch--writepid/run/openvpn@udp-ch.pid--status-version2
```

I really don't know what that means, but I guess it is supposed to be the command that was run... It seems weird that it includes no spaces, at least not as represented by the cat tool. However, when I open this file in vim, it shows "^@" whereever a space should apparently be:
`/usr/bin/openvpn^@--cd^@/etc/openvpn^@--config^@udp-ch.conf^@--daemon^@openvpn@udp-ch^@--writepid^@/run/openvpn@udp-ch.pid^@--status    -version^@2^@`

**Comment by doctorcolossus** [comment]
Now that I look at the command, I think the --cd argument must be what you are missing, since your script seems to be looking for the config file without knowing which folder to look in. From `man openvpn`:
```
       --cd dir
              Change directory to dir prior to reading any files such as configuration files, key files, scripts, etc.   dir  should
              be an absolute path, with a leading "/", and without any references to the current directory such as "." or "..".

              This  option  is useful when you are running OpenVPN in --daemon mode, and you want to consolidate all of your OpenVPN
              control files in one location.
```

**Comment by kb100** [comment]
@doctorcolossus See my attempted fix. https://github.com/kb100/i3blocks-contrib/tree/67-fix/openvpn

Use with -p as you tried before. Please let me know if it fixes your problem.

**Comment by kb100** [comment]
Also, according to `man proc` cmdline arguments are separated by null characters, so the "^@" are vim's way of showing you a null character. This is necessary since a cmdline argument may have a space in it. I added a quick check to see if the openvpn line has a --cd option and then prepend it to the config filename.

**Comment by doctorcolossus** [comment]
I just tried it and there are no more errors, but the output is:
```
down
down
```
The openvpn interface is up though:
```
$ systemctl status openvpn@*
● openvpn@udp-ch.service - OpenVPN connection to udp/ch
   Loaded: loaded (/etc/systemd/system/openvpn@udp-ch.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2016-12-30 16:26:04 MST; 21min ago
     Docs: man:openvpn(8)
  Process: 19623 ExecStart=/usr/bin/openvpn --cd /etc/openvpn --config %i.conf --daemon openvpn@%i --writepid /run/openvpn@%i.pid --status-version 2 (code=exited, status=0/SUCCESS)
 Main PID: 19624 (openvpn)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/system-openvpn.slice/openvpn@udp-ch.service
           └─19624 /usr/bin/openvpn --cd /etc/openvpn --config udp-ch.conf --daemon openvpn@udp-ch --writepid /run/openvpn@udp-ch.pid --status-version 2

Dec 30 16:26:07 xps openvpn@udp-ch[19624]: /usr/bin/ip link set dev tun0 up mtu 1500
Dec 30 16:26:07 xps openvpn@udp-ch[19624]: /usr/bin/ip addr add dev tun0 local 10.129.5.34 peer 10.129.5.33
Dec 30 16:26:12 xps openvpn@udp-ch[19624]: /usr/bin/ip route add 185.32.222.13/32 via 10.4.39.254
Dec 30 16:26:12 xps openvpn@udp-ch[19624]: /usr/bin/ip route add 0.0.0.0/1 via 10.129.5.33
Dec 30 16:26:12 xps openvpn@udp-ch[19624]: /usr/bin/ip route add 128.0.0.0/1 via 10.129.5.33
Dec 30 16:26:12 xps openvpn@udp-ch[19624]: /usr/bin/ip route add 216.146.43.70/32 via 10.4.39.254
Dec 30 16:26:12 xps openvpn@udp-ch[19624]: /usr/bin/ip route add 91.198.22.70/32 via 10.4.39.254
Dec 30 16:26:12 xps openvpn@udp-ch[19624]: /usr/bin/ip route add 216.146.38.70/32 via 10.4.39.254
Dec 30 16:26:12 xps openvpn@udp-ch[19624]: /usr/bin/ip route add 10.129.0.1/32 via 10.129.5.33
Dec 30 16:26:12 xps openvpn@udp-ch[19624]: Initialization Sequence Completed
```

**Comment by kb100** [comment]
Does your /etc/openvpn/udp-ch.conf have any lines like

    dev tun0

in it?

Also, can you post the output of `ls /sys/class/net` while the vpn is active?

**Comment by doctorcolossus** [comment]
Yes... I forgot to go back and follow the original instructions.
My config previously had `dev tun`.
After changing it to `dev tun0`, it works! Now the output is:
```
ch
up
```
You probably don't need this any more then, but as requested:
```
$ ls /sys/class/net
lo  tun0  wlp2s0
```
Is there not some way to get around hard-coding the interface name? I have different configs for different countries ('ch' is Switzerland's country-code). My config files are mostly unmodified, as provided by my VPN supplier. Personally, I usually just tunnel through one at a time, but I know there are paranoid folks out there who use multiple layers of VPN, and I can imagine they might switch up the order arbitrarily.

**Comment by kb100** [comment]
We don't moderate how you should use your VPN(s), the blocklet should work regardless. I'm not the author of this blocklet and I can't really even test it since I don't have a VPN. I'm just trying to patch it from reading man pages and using your info.

Could you explain to me what the line `dev tun` was supposed to mean? How did `tun` get translated to `tun0` at runtime? The man page says it means "dynamic tun device" but I don't understand. Does that mean "use tunX, where X is the smallest number such that tunX is not an existing tun device"?
I'm afraid that may be the case, and in that case if a VPN goes down, how can one tell which tunX device is associated to which openvpn instance?

**Comment by doctorcolossus** [comment]
> Does that mean "use tunX, where X is the smallest number such that tunX is not an existing tun device"?
Yes, precisely. At least that's my understanding and has been my experience so far. I didn't write this configuration though. The line was included in the config provided by the company which runs my VPN server. I would assume that they know what they're doing and that this is thus a common practice. Anyway, their configurations work great for me.
> I'm afraid that may be the case, and in that case if a VPN goes down, how can one tell which tunX device is associated to which openvpn instance?
Well, in my particular case at least, systemctl provides all of this information. Otherwise, I am not sure... :| I will let you know if I think of any ideas.

**Comment by kb100** [comment]
Closing for now and made a note that dynamic devices are not (yet) supported. May reopen in future if someone knows enough to add support.
