### ISSUE TITLE
volume-pulseaudio fails to grep "proper" device name

### ISSUE THREAD

**Issue by LordTaifleh** [vivien/i3blocks-contrib#70]
The volume-pulseaudio block should output a nice-to-read name for all output sinks.
That's not the case for (my) virtual output devices. I have a combined device, that outputs sound to two devices simultaneously and a virtual output sink for dlna via pulseaudio-dlna. Hence the block fails to get a good name from pacmd list-sinks.

The culprit is sed in lin 81:
`81: NAME=$(echo "$NAME" | sed 's/.*\.\(.*\)>/\1/') `

Maybe the block should check the name string for dots " . " and if no dots are there, set the name to the string betwen the "<>".
The `device.descripton` in properties seems like a good source for device names also, if long Strings were cut to a minimum in length. portability remains a problem then.
There's also `alsa.mixer_name` and `alsa.card_name`, but these also do not apply to virtual devices.
What do?

### i3blocks config relevant to blocklet(s)
```
[volume-pulseaudio]
command=$HOME/.config/i3blocks/blocklets/volume-pulseaudio -F 1 -p -c dc322f -C eee8d5
interval=once
signal=-RTMIN+1
```

### Output of blocklet(s) when run from command line
```
$ ./volume-pulseaudio -p  -c dc322f -C eee8d5 
  15 [2:name: <combined>]
  15 [2]
dc322f
```

### Output of any relevant other commands that might help diagnostics
the package `paprefs` offers the option to add a virtual device,
`pulseaudi-dlna` offers a dlna  sink. both deliver names that fail to get red by the block:
```
$ pacmd list-sinks   #omitted the first two devices since those work fine
* index: 2
	name: <combined>
	driver: <module-combine-sink.c>
	flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: SUSPENDED
	suspend cause: IDLE 
	priority: 1000
	volume: front-left: 0 /   0% / -inf dB,   front-right: 0 /   0% / -inf dB
	        balance 0.00
	base volume: 65536 / 100% / 0.00 dB
	volume steps: 65537
	muted: yes
	current latency: 0.00 ms
	max request: 4 KiB
	max rewind: 0 KiB
	monitor source: 2
	sample spec: s16le 2ch 44100Hz
	channel map: front-left,front-right
	             Stereo
	used by: 0
	linked by: 1
	configured latency: 0.00 ms; range is 0.50 .. 200.00 ms
	module: 16
	properties:
		device.class = "filter"
		device.description = "Simultaneous output to Built-in Audio Digital Surround 7.1 (HDMI), Built-in Audio Analog Stereo"
		device.icon_name = "audio-card"
* index: 3
	name: <np1100_dlna>
	driver: <module-null-sink.c>
	flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: IDLE
	suspend cause: 
	priority: 1000
	volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	        balance 0.00
	base volume: 65536 / 100% / 0.00 dB
	volume steps: 65537
	muted: no
	current latency: 13.14 ms
	max request: 6 KiB
	max rewind: 6 KiB
	monitor source: 3
	sample spec: s16le 2ch 44100Hz
	channel map: front-left,front-right
	             Stereo
	used by: 0
	linked by: 1
	configured latency: 40.00 ms; range is 0.50 .. 2000.00 ms
	module: 30
	properties:
		device.description = "NP1100 (DLNA)"
		device.class = "abstract"
		device.icon_name = "audio-card"

```

**Comment by kb100** [comment]
I took your suggestion of using <combined> if no period is found. Also added option for using ALSA names if they exist.

**Comment by LordTaifleh** [comment]
confirm fixed status. thank you!
