### ISSUE TITLE
Default player doesn't consider cmus

### ISSUE THREAD

**Issue by dsibenik** [vivien/i3blocks-contrib#71]
### Expected behavior
If I don't give an exact instance in i3blocks, it should check for players and check for cmus

### Actual behavior
It just checks for players, not cmus
if I make it instance=cmus it works, but then the other players are ignored
if I make it instance=mps-youtube it works, but then cmus is ignored

**Comment by kb100** [comment]
Unfortunately, the blocklet is not intended to handle all media players simultaneously. Doing so would increase the complexity of the blocklet substantially and require an entire rewrite. As the sole maintainer of this repo I can tell you now that such a rewrite is not in my time budget. However, I would seriously review a pull request if you (or someone else) wants to take the time to implement it. Until then I'm closing this as: feature request, probably won't implement.

**Comment by captn3m0** [comment]
`playerctl` now supports 2 usecases:

- If you run `playerctld`, it will automatically target the last active player.
- Using `--all-players` will target all players.

I think we can easily ask users to run `playerctld` and make the instance parameter optional?

**Comment by captn3m0** [comment]
Found a workaround: 

`instance=%any` works for now.

You can prefer a player by `cmus,%any`
