### ISSUE TITLE
shutdown_menu editing options makes rofi fail

### ISSUE THREAD

**Issue by LordTaifleh** [vivien/i3blocks-contrib#74]
### Expected behavior
adding desired options to ROFI_OPTIONS should not affect the succes of launching rofi

### Actual behavior
shutdown_menu or rather rofi produces rubbish, when the following is added to ROFI_OPTIONS
`-m -3 -theme-str '#window { anchor: southeast;}'`
`-m -3` puts rofi to the location of the cursor, 
`-theme-str '#window { anchor: southeast;}'` should make rofi display to the northwest of the cursor

this is not a rofi issue, as it works in other scripts

### i3blocks config relevant to blocklet(s)
shutdown_menu
### i3blocks.conf
```
[shutdown_menu]
full_text=
color=#eee8d5
command=$HOME/.config/i3blocks/blocklets/shutdown_menu && echo ""
```

### Output of blocklet(s) when run from command line
none, rofi fails though with an error about parsing
i suspect missing qutation of the options as the culprit

**Comment by kb100** [comment]
Hi, please post the portion of your i3blocks config (usually i3blocks.conf, or ~/.config/i3blocks/config) relevant to this issue. 

"none, rofi fails though with an error about parsing" please post the error that you receive when run from the command line.

**Comment by LordTaifleh** [comment]
i updated the post to show my i3blocks config, but the block doesnt output anything on failure.

**Comment by kb100** [comment]
@LordTaifleh I believe my commit https://github.com/kb100/i3blocks-contrib/commit/03491e8d4b986549f4c004495f9bf83b0833ccf1 fixes your issue. Will you please test it?

**Comment by LordTaifleh** [comment]
it's still the same. rofi parser cant parse the argument #window it says in the opening window.

**Comment by kb100** [comment]
@LordTaifleh are you sure you checked out my commit and didn't just try to pull new updates from this repo? Github tells me there have been no clones on my fork. I tested with

    ROFI_OPTIONS=(-width -11 -location 3 -hide-scrollbar -bw 2 -m -3 -theme-str '#window { anchor: southeast;}' )

and it works for me with commit https://github.com/kb100/i3blocks-contrib/commit/03491e8d4b986549f4c004495f9bf83b0833ccf1

Note: if you are using the wrong commit the above won't work.

**Comment by LordTaifleh** [comment]
i'm sure i did it alright, all the edits you made appear in my shutdown_menu file.
running `bash -x shutdow_menu` gives me this output: ` rofi -dmenu -i -lines 8 -p Menu: -bc -width -11 -location 3 -hide-scrollbar -bw 2 -m -3 -theme-str '#window' '{' anchor: 'southeast;}'`

**Comment by kb100** [comment]
@LordTaifleh  it should be 

    '#window { anchor: southeast;}'

not 

    '#window' '{' anchor: 'southeast;}'

I'm guessing in your config you put

    ROFI_OPTIONS=(-width -11 -location 3 -hide-scrollbar -bw 2 -m -3 -theme-str #window { anchor: southeast;} )

instead of 

    ROFI_OPTIONS=(-width -11 -location 3 -hide-scrollbar -bw 2 -m -3 -theme-str '#window { anchor: southeast;}' )

**Comment by LordTaifleh** [comment]
nope i'm sorry, I put the ' in the right places
i know it shouldn't be that way, that's why it doesn't work

**Comment by LordTaifleh** [comment]
can you push the thing with the #window arguments, the way it works for you?

**Comment by kb100** [comment]
I just ran with bash -x and it showed me 

    rofi -dmenu -i -lines 8 -p Menu: -bc -width -11 -location 3 -hide-scrollbar -bw 2 -m -3 -theme-str '#window' '{' anchor: 'southeast;}'

exactly like yours (so what it is trying to run is correct). This is not an error. The menu came up at that point. If it failed at that point for you then perhaps you forgot to install rofi?

**Comment by LordTaifleh** [comment]
this is so weird, when i put that line in my cmd, then it fails. yes i do have rofi installed :D
do you use the latest version of rofi? i do.

**Comment by kb100** [comment]
Can you please post the exact error it is giving you? Or are you saying the script runs without error and the menu just doesn't popup? Because before you made it sound like it was giving you a parsing error.

When I run from the command line

    rofi -dmenu -i -lines 8 -p Menu: -bc -width -11 -location 3 -hide-scrollbar -bw 2 -m -3 -theme-str '#window' '{' anchor: 'southeast;}'

It pops up a blank loading menu (you have to pipe stuff to rofi to tell it what the options are).

My rofi is from debian stretch repository Version: 1.3.1

**Comment by kb100** [comment]
Also here are some things to help you troubleshoot:

Even if you have the latest version of rofi installed, you may have an older copy of rofi that is running instead of the newer one, e.g. if you built from source and installed to /usr/local/bin, this will override anything your package manager puts in /usr/bin. run `rofi -v` to make sure the version is correct. Same for i3 and i3blocks if you ever installed them from source.

**Comment by LordTaifleh** [comment]
ok, for me it opens a slim white window with an error message about how rofi detected errors on startup.
however, this is how the command **should** look like:
`echo "a\nb\nc\nd" |  rofi -dmenu -i -lines 8 -p Menu: -bc -width -11 -location 3 -hide-scrollbar -bw 2 -m -3 -theme-str '#window { anchor: southeast;}'
`
that line works for me.

**Comment by LordTaifleh** [comment]
note how the argument after theme-str is embraced in one single set of single quotes

**Comment by kb100** [comment]
@LordTaifleh OK I think it's fixed for real now: I amended the commit: https://github.com/kb100/i3blocks-contrib/commit/51aaa142faae46781ae844f1833c119c2b30586d

**Comment by LordTaifleh** [comment]
@kb100 yes, latest commit 51aaa14 fixes the issue. Thank you for your time!

**Comment by kb100** [comment]
@LordTaifleh :hand: high five
