### ISSUE TITLE
wifi-connection manager block. kind of.

### ISSUE THREAD

**Issue by vKnmnn** [vivien/i3blocks-contrib#75]
I wrote a patch to` netctl/wifi-menu` to get a `rofi-wifi-menu`
since it's more a netctl patch than a blocklet, would you still consider adding it?
If you would like to check it out, you can find it here on github.
the corresponding blocklet is a slightly edited version of the ssid blocklet i had in my blocklets folder.
It displays red output when no internet connection is available and has added click options for the wifi-menu

**Comment by kb100** [comment]
I would definitely consider merging a wifi menu script. To make the process quicker, make sure to follow the contributing guidelines: https://github.com/vivien/i3blocks-contrib/blob/master/CONTRIBUTING.md

**Comment by vKnmnn** [comment]
as an update, scratch that wifi-menu patching. it's crusty. I'm currently writng this with the help of wpa_cli, but it should still be possible to write a netctl profile from that (or any other wifi-manager)
I'll keep you updated

**Comment by kb100** [comment]
Closing for now. If this is related to a PR but not mentioned, I will get to it... eventually...
