### ISSUE TITLE
Openvpn indicator does not work

### ISSUE THREAD

**Issue by guest73** [vivien/i3blocks-contrib#85]
### Expected behavior
Who knows? Must show something about my running VPN connection

### Actual behavior
Always shows VPN:down message

### i3blocks config relevant to blocklet(s)
[openvpn]
instance=tun0
interval=10

### Output of blocklet(s) when run from command line
VPN: down
VPN: down

### Output of any relevant other commands that might help diagnostics
1) I am on Mangaro XFCE 17.
2) There is no /run/openvpn folder.
3) There are /run/openvpn-client and /run/openvpn-server folders but they are always empty no meter if my VPN is running or not.
4) folder in /sys/class/net/tun0 exists and is not empty
5) I searched all my system for *.pid files, found only 3 total not related to openvpn
VPN is working ok

**Comment by kb100** [comment]
Can you read through this thread https://github.com/vivien/i3blocks-contrib/issues/67. I think your issue may be the same. Essentially it comes down to "the script doesn't support dynamic devices". In your openvpn config file (usually /etc/openvpn/udp-ch.conf) you need to hardcode tun0
    
    dev tun0

instead of having

    dev tun

**Comment by guest73** [comment]
I do not start my VPN by putting anything into /etc/openvpn. This will not work for me. I just run it with --config option. My VPN requires an Google Authenticator numbers be prepended each time I must enter a password.

**Comment by kb100** [comment]
In that case you will have to also use openvpn's --writepid option when you start it, and the blocklets -p option to match.

**Comment by guest73** [comment]
Ok. Thanks for helping me out.
I set the --writepid in my config file. So I put it like this
--writepid /home/[myacc]/[project]/vpn-setup/proc/[myname]-vpn.pid
and then run it like this:
/usr/lib/i3blocks/openvpn -p '/home/[myacc]/[project]/vpn-setup/proc/[myname]-vpn.pid'
but the output is still
VPN: down
VPN: down
The VPN is working and I set dev tun0 in my vpn configuration

**Comment by kb100** [comment]
While your vpn is running, can you verify that openvpn actually writes the pid file to the location you specified? Also, by any chance does your [myacc] or [project] or [myname] contain any spaces?

**Comment by guest73** [comment]
1) The pid file is where it suppose to be, confirmed
2) [myacc] - a simple one word with only english characters
3) [project] - a simple one word with only english characters, but it's a symlink to a subfolder of Project folder so [project]->[/home/[myacc]/Projects/[the_same_only_English_letters]
3)[myname] - serser :)
4) The output does not indicate any error. Just print 2 'down's

**Comment by kb100** [comment]
Hmm... only other obvious thing to check is does your config file name end in .conf? The script assumes this. If not, could you try adding print statements in various places of the script to see where exactly it is exiting?

**Comment by guest73** [comment]
Yey! It works now! Thanks mate! That was the problem.

**Comment by guest73** [comment]
One remark, though. It does run successful only from the folder where a configuration file is located. If I try it from any other folder or from the script it end's up with an error
_Can't read config file 'serser.conf': No such file or directory_
How can I overcome this? Copy my configuration file into usr/lib/i3blocks/ ?

**Comment by guest73** [comment]
Ok. making symlink of my serser.conf into the /usr/lib/i3blocks/ did the trick. Now it's finally on my bar working as expected. Thanks again.

**Comment by kb100** [comment]
Use the `--cd` option that openvpn provides.

**Comment by andersfylling** [comment]
I had to make a symlink into my home dir in order for this to work. Tried messing around with the `--cd` options, but that didn't help.
