### ISSUE TITLE
Explicitly allow/encourage multiple blocks that accomplish the same task

### ISSUE THREAD

**Issue by kb100** [vivien/i3blocks-contrib#9]
The purpose of this issue is to resolve the logistical details of allowing multiple scripts that support the same functionality. The result will hopefully be a section in the contributing guidelines making clear our policies on the matter.

There are many different ways to write the same blocklet. Some people don't want certain dependencies. Some people like one look and feel over another. Some people want bells and whistles. Some people want minimalism. Users should have the ability to easily browse all their options and pick the one that is best for them, without necessarily altering a script themselves.

I think that we should pave a road for contributers to develop scripts that accomplish the same task as other scripts.

I propose leaving the directory structure the same as it is currently until a duplicate or similar purpose script wants to be contributed. In that event, we will make a directory for the category of script being contributed, and migrate the preexisting script's folder into that directory. For example.

Before:

    /script1
    /script2
    /batteryscript
    /script4

After:

    /script1
    /script2
    /battery
        README.md
        /batteryscript
        /batteryalt
    /script4

where the `README.md` delineates what types of scripts should be put in that folder.

What are your thoughts on duplicate blocklets, naming conventions, etc?

**Comment by Nycroth** [comment]
I think this makes sense. This repository should argragate all scripts and as collections of congruent scripts emerge, agragating them in a single subdirectory makes sense. I'll add this to the Wiki and contributing guidelines soon.

**Comment by vivien** [comment]
I agree with you @kb100 too. Feel free to patch the contributing guidelines!

**Comment by kb100** [comment]
The wiki has been updated to say we allow multiple blocklets accomplishing the same thing.
