### ISSUE TITLE
Battery module on click action, doesn't want to work

### ISSUE THREAD

**Issue by Pxmme** [vivien/i3blocks-contrib#98]
### Expected behavior

When I do a left-click on my battery icon in the i3 bar, it changes the display from "battery bar" to "battery bar + time left". When I right click it, it comes back to only displaying "battery bar" again.

### Actual behavior

When I put my little piece of code in the script, it simply wouldn't work at all. I don't have any display of battery no more with my little mod in.

### i3blocks config relevant to blocklet(s)

```if ($status eq 'Discharging') {
        $full_text .= '';
} elsif ($status eq 'Charging') {
        $full_text .= ' ';
        $full_text .= " ($percent%)";
}

$short_text = $full_text;

######### MY MOD ###########

case $BLOCK_BUTTON in
    1) $full_text .= " ($1)";} ;;
    3) $full_text = $short_text ;;
esac
```

### Output of blocklet(s) when run from command line

```
[pomme@david i3blocks]$ ./battery
Number found where operator expected at ./battery line 71, near "in
    1"
	(Do you need to predeclare in?)
Scalar found where operator expected at ./battery line 71, near ") $full_text"
	(Missing operator before $full_text?)
Scalar found where operator expected at ./battery line 72, near ") $full_text"
	(Missing operator before $full_text?)
Global symbol "$BLOCK_BUTTON" requires explicit package name (did you forget to declare "my $BLOCK_BUTTON"?) at ./battery line 70.
syntax error at ./battery line 71, near "in
    1"
Unmatched right curly bracket at ./battery line 71, at end of line
syntax error at ./battery line 72, near "3) "
syntax error at ./battery line 81, near "esac


################################



# print text
print"
Execution of ./battery aborted due to compilation errors.

```

### Output of any relevant other commands that might help diagnostics

I just want to say that, my battery sends the good information to my system, because when I only try to display $1, which is the variable that contains the estimated time left, it works without a problem.

Also, please excuse me for any bad english I might have used here : it is not my native tongue.

Thanks!

**Comment by kb100** [comment]
It seems like the battery blocklet you are referring to is not either of the battery blocklets in this repository. It looks like a modification of the battery script from the i3blocks repository. That blocklet is written in perl, but your modification is written in bash. In perl, one uses a switch statement, which is equivalent to bash's case-in statement. http://perldoc.perl.org/5.8.8/Switch.html

This isn't really an issue with i3blocks or i3blocks-contrib, so I'm closing the issue. If you aren't able to modify the battery script to your liking, you may want to try using either of the battery scripts provided in this repository, which may be more to your liking.
